language: node_js
node_js:
  - 'stable'
  - 'lts/*'

before_install:
  - npm install -g yarn
  - npm install -g lerna
install:
  - lerna bootstrap
script:
  - yarn build
  - yarn test

dist: trusty
sudo: false

