language: node_js
node_js:
  - 'stable'
  - 'lts/*'

before_install:
  - npm install -g yarn
script:
  - cd packages/chamber-core;yarn build;cd ../../
  - yarn run-all test

dist: trusty
sudo: false

